"""empty message

Revision ID: f39c85b7f4b0
Revises: bf55ae167575
Create Date: 2023-01-05 10:21:29.216764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39c85b7f4b0'
down_revision = 'bf55ae167575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('owner', sa.String(), nullable=True))
    op.drop_column('board', 'owners_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('owners_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('board', 'owner')
    # ### end Alembic commands ###
